import { bool, irreversible, num, read, str, write, type ToolTemplate } from "./tool-templates";

/**
 * The tool catalogue, sector by sector, in the order the agent catalogue runs.
 *
 * Every parameter description is written for the model, which reads it to decide what to
 * pass: "the booking reference the caller read out, letters and digits" tells it more than
 * "reference". Every spoken sentence reads from a small, flat response — `status`,
 * `date`, `time`, `amount` — because a Nigerian business wiring its first API is more likely
 * to have a spreadsheet behind a webhook than a schema, and a flat shape is the one a
 * person can produce in an afternoon. Amounts are spoken as naira by the normalizer; a
 * template never spells out the currency.
 */

/* ------------------------------------------------------------ any business */
const GENERAL: readonly ToolTemplate[] = [
  read({
    id: "look-up-customer", sector: "Any business",
    name: "look_up_customer",
    summary: "Finds a customer by phone number so the agent can greet a known caller and see their account.",
    description: "Look up an existing customer by the phone number they are calling from or gave. Use it at the start of a call to see whether the caller is known.",
    path: "/customers", params: [str("phone", "The caller's phone number, digits only, as they gave it or as it appears on the call.")],
    expects: "name, since (when they became a customer), openItems (a count of open orders or tickets).",
    speech: "I can see you, {name} — a customer with us since {since}. You have {openItems} open items with us.",
    fallback: "I couldn't find an account under that number, but I can still help.",
  }),
  write({
    id: "create-ticket", sector: "Any business",
    name: "create_ticket",
    summary: "Logs a support ticket in the caller's words, with a category and their number, and speaks the reference.",
    description: "Create a support ticket for something the caller needs a person to handle. Use it after taking their name, number and what the issue is.",
    path: "/tickets",
    params: [str("name", "The caller's full name."), str("phone", "The number to call back on, digits only."), str("category", "One of: sales, support, billing, complaint, other."), str("summary", "What the caller said the issue is, in one or two sentences.")],
    readback: "I'll log this for {name} on {phone}: {summary}. Shall I go ahead?",
    expects: "reference (the ticket number), team (who will pick it up), by (when they will respond, as a phrase).",
    speech: "That's logged — your reference is {reference}. The {team} team will be in touch by {by}.",
    fallback: "I've noted it, though I couldn't get a reference number just now. Somebody will still call you back.",
  }),
  read({
    id: "check-ticket-status", sector: "Any business",
    name: "check_ticket_status",
    summary: "Reads back the status of a ticket the caller has a reference for.",
    description: "Check the status of an existing support ticket. Use it when the caller gives a ticket or case reference.",
    path: "/tickets/{reference}", params: [str("reference", "The ticket reference the caller read out, letters and digits, no spaces.")],
    expects: "status (a short phrase), owner (who has it), updated (when it last moved, as a phrase).",
    speech: "Ticket {reference} is {status}. It's with {owner}, and it was last updated {updated}.",
    fallback: "I can't find a ticket with that reference. Could you read it to me once more?",
  }),
  read({
    id: "look-up-invoice", sector: "Any business",
    name: "look_up_invoice",
    summary: "Reads an invoice's amount, due date and whether it has been paid.",
    description: "Look up an invoice by its number to say the amount, the due date and whether it is paid. Use it for any question about a bill.",
    path: "/invoices/{number}", params: [str("number", "The invoice number as printed on the invoice.")],
    expects: "amount (a number in naira), due (a date phrase), status (paid, unpaid, overdue, part-paid).",
    speech: "Invoice {number} is for {amount} naira, due {due}, and it's currently {status}.",
    fallback: "I can't find an invoice with that number. It may be under a different number, so accounts will check and call you back.",
  }),
  write({
    id: "schedule-callback", sector: "Any business",
    name: "schedule_callback",
    summary: "Books a call back from a named team at a time the caller chose.",
    description: "Schedule a call back from a team at a time the caller prefers. Use it when a person needs to call them and they have said when.",
    path: "/callbacks",
    params: [str("phone", "The number to call, digits only."), str("team", "Which team should call: sales, support, accounts, or management."), str("when", "The day and time the caller asked for, as they said it."), str("about", "What the call is about, in one sentence.")],
    readback: "So {team} will call you on {phone} {when}, about {about}. Is that right?",
    expects: "confirmed (yes or no), slot (the agreed time as a phrase).",
    speech: "Done — you'll get a call {slot}.",
    fallback: "I've asked for the call back, though I couldn't confirm the exact time. They will call as close to it as they can.",
  }),
];

/* ---------------------------------------------------------------- property */
const PROPERTY: readonly ToolTemplate[] = [
  read({
    id: "look-up-listing", sector: "Property",
    name: "look_up_listing",
    summary: "Reads a property listing — type, area, price and whether it's still available — from its reference.",
    description: "Look up a property listing by its reference to say what it is, where, the price and whether it is still available. Use it when a caller names a listing.",
    path: "/listings/{reference}", params: [str("reference", "The listing reference from the advert, letters and digits, no spaces.")],
    expects: "type (e.g. two bedroom flat), area, price (a number in naira), status (available, under offer, let, sold).",
    speech: "That's a {type} in {area}, listed at {price} naira, and it's currently {status}.",
    fallback: "I can't find a listing with that reference. An agent will check it and call you back.",
  }),
  read({
    id: "search-listings", sector: "Property",
    name: "search_listings",
    summary: "Finds available properties by area, type, budget and rent-or-buy, and speaks the closest match.",
    description: "Search available properties by area, type and budget. Use it once the caller has said whether they are renting or buying, where, what kind of place, and their budget.",
    path: "/listings",
    params: [str("intent", "rent or buy."), str("area", "The area the caller named."), str("type", "The kind of property: self-contain, mini flat, two bedroom, three bedroom, duplex, land, or any.", false), num("budget", "The caller's budget in naira, per year for rent or total for a purchase.")],
    expects: "count (how many matched), top.reference, top.type, top.area, top.price (the closest match).",
    speech: "I found {count} that fit. The closest is a {top.type} in {top.area} at {top.price} naira — reference {top.reference}.",
    fallback: "Nothing matches that exactly right now, but an agent will look wider and call you back with options.",
  }),
  read({
    id: "check-viewing-slots", sector: "Property",
    name: "check_viewing_slots",
    summary: "Checks which viewing times are free for a property on a given day.",
    description: "Check the free viewing slots for a property on a day. Use it before booking a viewing so the caller picks a time that is actually free.",
    path: "/listings/{reference}/slots", params: [str("reference", "The listing reference from the advert."), str("date", "The day the caller wants, as a date.")],
    expects: "count, first (the earliest free slot as a time phrase), last (the latest).",
    speech: "There are {count} slots free that day, from {first} to {last}. Which suits you?",
    fallback: "There are no viewings free that day. Would another day work?",
  }),
  write({
    id: "book-viewing", sector: "Property",
    name: "book_viewing",
    summary: "Books a viewing for a listing at a day and time, under the caller's name and number, and speaks the confirmation.",
    description: "Book a viewing of a property. Use it after the caller has chosen a listing, a day and a time, and you have their name and number.",
    path: "/viewings",
    params: [str("reference", "The listing reference from the advert."), str("name", "The caller's full name."), str("phone", "The caller's number, digits only."), str("date", "The day of the viewing, as a date."), str("time", "The time of the viewing, as a clock time.")],
    readback: "I'll book {reference} for {name} on {date} at {time}, and text {phone}. Shall I confirm?",
    expects: "confirmation (a reference), agent (who will meet them), address.",
    speech: "Booked — your confirmation is {confirmation}. {agent} will meet you at {address}. Please bring an ID.",
    fallback: "The booking went through, though I couldn't get the confirmation number. The agent will text you the details.",
  }),
  write({
    id: "log-maintenance-fault", sector: "Property",
    name: "log_maintenance_fault",
    summary: "Logs a fault for a flat with its urgency and speaks the job number.",
    description: "Log a maintenance fault for a resident. Use it after taking the block and flat, what the fault is and whether it can wait.",
    path: "/faults",
    params: [str("unit", "The block and flat number as the resident gave it."), str("phone", "The resident's number, digits only."), str("fault", "What is wrong, in the resident's words."), bool("urgent", "True if the resident said it cannot wait — no water, no power, a leak, a lift.")],
    readback: "Logging for {unit}: {fault}. I'll mark it urgent: {urgent}. Go ahead?",
    expects: "job (a job number), scheduled (when a technician is due, as a phrase).",
    speech: "Logged — job number {job}. A technician is scheduled {scheduled}.",
    fallback: "It's logged, though I couldn't get a job number just now. Facility management will call you with the technician's time.",
  }),
  read({
    id: "check-service-charge", sector: "Property",
    name: "check_service_charge",
    summary: "Reads a flat's service charge balance and due date, for the resident on record only.",
    description: "Check the service charge balance for a flat. Use it only for the resident on record, after they have given their block and flat number.",
    path: "/units/{unit}/charges", params: [str("unit", "The block and flat number.")],
    expects: "balance (a number in naira, zero when paid), due (a date phrase), lastPayment (a date phrase).",
    speech: "The balance on {unit} is {balance} naira, due {due}. The last payment was {lastPayment}.",
    fallback: "I can't see that flat's charges right now. Accounts will check and call you back.",
  }),
  irreversible({
    id: "terminate-tenancy", sector: "Property",
    name: "terminate_tenancy",
    summary: "Ending a tenancy or releasing a deposit — never on the phone; always a person.",
    description: "Give notice on a tenancy, or release a deposit. Never do this yourself.",
    path: "/tenancies/{reference}/terminate", params: [str("reference", "The tenancy reference.")],
    transferReason: "Ending a tenancy has to be confirmed in writing with the property manager, so I'm putting you through to them now.",
  }),
];

/* ------------------------------------------------------ hospitality & food */
const HOSPITALITY: readonly ToolTemplate[] = [
  read({
    id: "check-room-availability", sector: "Hospitality & food",
    name: "check_room_availability",
    summary: "Checks whether a room type is free for the dates and speaks the nightly rate.",
    description: "Check whether a room type is available between two dates and what it costs a night. Use it once the caller has said their dates and the room they want.",
    path: "/rooms/availability",
    params: [str("roomType", "standard, deluxe, executive, or suite."), str("checkIn", "The date they arrive, as a date."), num("nights", "How many nights they will stay.")],
    expects: "available (yes or no), rate (nightly, a number in naira), roomsLeft (a count).",
    speech: "A {roomType} is available for those dates at {rate} naira a night. There are {roomsLeft} left.",
    fallback: "That room type is fully booked for those dates. Would a different room, or different dates, work?",
  }),
  write({
    id: "create-reservation", sector: "Hospitality & food",
    name: "create_reservation",
    summary: "Reserves a room under the caller's name for the dates and speaks the reference.",
    description: "Make a room reservation. Use it after availability is confirmed and you have the caller's name and number.",
    path: "/reservations",
    params: [str("name", "The guest's full name."), str("phone", "The guest's number, digits only."), str("roomType", "standard, deluxe, executive, or suite."), str("checkIn", "The date they arrive, as a date."), num("nights", "How many nights they will stay."), num("guests", "How many guests will stay.")],
    readback: "I'll reserve a {roomType} for {name}, arriving {checkIn} for {nights} nights, {guests} guests. Shall I confirm?",
    expects: "reference, holdUntil (when the room is held until, as a phrase), total (a number in naira).",
    speech: "Reserved — reference {reference}. The room is held until {holdUntil}, and the total is {total} naira. A payment link is on its way by text.",
    fallback: "The reservation went through, though I couldn't get the reference just now. Reservations will text it to you.",
  }),
  read({
    id: "look-up-reservation", sector: "Hospitality & food",
    name: "look_up_reservation",
    summary: "Reads a reservation's dates, room and status for the guest who made it.",
    description: "Look up a reservation by its reference or the guest's phone number. Use it when a guest asks about their booking.",
    path: "/reservations/{reference}", params: [str("reference", "The booking reference, or the phone number it was made with.")],
    expects: "name, roomType, checkIn (a date phrase), nights, status (confirmed, pending payment, cancelled).",
    speech: "I have a {roomType} for {name}, arriving {checkIn} for {nights} nights. It's {status}.",
    fallback: "I can't find a reservation under that. Could it be under another name or number?",
  }),
  irreversible({
    id: "cancel-reservation", sector: "Hospitality & food",
    name: "cancel_reservation",
    summary: "Cancelling a reservation — a person confirms it, because of the charge under the booking's terms.",
    description: "Cancel a reservation. Never do this yourself; a person confirms the cancellation and any charge.",
    path: "/reservations/{reference}/cancel", params: [str("reference", "The booking reference the caller was given.")],
    transferReason: "A cancellation can carry a charge under the booking's terms, so reservations confirm it with you directly. Putting you through now.",
  }),
  read({
    id: "check-table-availability", sector: "Hospitality & food",
    name: "check_table_availability",
    summary: "Checks whether a table for a party is free at a day and time.",
    description: "Check whether a table is free for a number of people at a day and time. Use it before booking a table.",
    path: "/tables/availability", params: [str("date", "The day they want, as a date."), str("time", "The time they want, as a clock time."), num("party", "How many people the table is for.")],
    expects: "available (yes or no), nearest (the nearest free time if the asked-for one is not, as a phrase).",
    speech: "A table for {party} at {time} — available: {available}. The nearest free time is {nearest}.",
    fallback: "We're full at that time. Would a little earlier or later work?",
  }),
  write({
    id: "book-table", sector: "Hospitality & food",
    name: "book_table",
    summary: "Books a table under the caller's name and speaks the confirmation.",
    description: "Book a table. Use it after checking availability and taking the caller's name and number.",
    path: "/tables/bookings",
    params: [str("name", "The name for the booking."), str("phone", "Their number, digits only."), str("date", "The day they want, as a date."), str("time", "The time they want, as a clock time."), num("party", "How many people the table is for."), str("note", "Anything to note — a birthday, a high chair, a quiet corner.", false)],
    readback: "A table for {party} under {name}, on {date} at {time}. Shall I book it?",
    expects: "confirmation, holdMinutes (how long the table is held past the time).",
    speech: "Booked — confirmation {confirmation}. We hold the table for {holdMinutes} minutes past the time.",
    fallback: "The booking went through, though I couldn't get the confirmation. You'll get a text shortly.",
  }),
  write({
    id: "place-order", sector: "Hospitality & food",
    name: "place_order",
    summary: "Places a takeaway or delivery order in the caller's words and speaks the total and the time.",
    description: "Place a food order for delivery or pickup. Use it after reading the items back and taking the address for a delivery.",
    path: "/orders",
    params: [str("name", "The caller's full name."), str("phone", "Their number, digits only."), str("items", "The order, item by item with quantities, as the caller said it."), str("mode", "delivery or pickup."), str("address", "The delivery address with a landmark, or empty for pickup.", false)],
    readback: "Your order: {items}, for {mode}. Shall I send it to the kitchen?",
    expects: "orderNumber, total (a number in naira), ready (when it will be ready or delivered, as a phrase).",
    speech: "Order {orderNumber} is in. The total is {total} naira, and it'll be {ready}.",
    fallback: "The order went to the kitchen, though I couldn't get the total just now. It will be confirmed by text before it goes out.",
  }),
  read({
    id: "track-order", sector: "Hospitality & food",
    name: "track_order",
    summary: "Reads where an order is — in the kitchen, with the rider, delivered.",
    description: "Check the status of a food order by its number. Use it when a caller asks where their order is.",
    path: "/orders/{orderNumber}", params: [str("orderNumber", "The order number from the confirmation.")],
    expects: "status (preparing, with the rider, delivered), eta (a phrase), rider (a name, when out for delivery).",
    speech: "Order {orderNumber} is {status}. It should be with you {eta}.",
    fallback: "I can't see that order number. Could you check the confirmation text and read it again?",
  }),
];

/* -------------------------------------------------------------- healthcare */
const HEALTHCARE: readonly ToolTemplate[] = [
  read({
    id: "find-appointment-slots", sector: "Healthcare",
    name: "find_appointment_slots",
    summary: "Finds free appointment slots in a department on a day.",
    description: "Find free appointment slots in a department on a given day. Use it before booking so the patient picks a time that is actually free.",
    path: "/appointments/slots", params: [str("department", "general practice, paediatrics, antenatal, dental, or the specialist named."), str("date", "The day the patient wants.")],
    expects: "count, first (earliest free time, a phrase), last (latest), doctor (who is on that day).",
    speech: "{doctor} is on that day with {count} slots free, from {first} to {last}. What time suits you?",
    fallback: "There's nothing free in that department that day. Would another day work?",
  }),
  write({
    id: "book-appointment", sector: "Healthcare",
    name: "book_appointment",
    summary: "Books an appointment for a patient and speaks the confirmation and what to bring.",
    description: "Book an appointment. Use it after a slot is chosen and you have the patient's name, number and hospital number if they have one.",
    path: "/appointments",
    params: [str("patientName", "The patient's name."), str("phone", "A number for the confirmation text, digits only."), str("hospitalNumber", "The hospital number from the patient's card, if they have one.", false), str("department", "The department the appointment is in."), str("date", "The day they want, as a date."), str("time", "The time they want, as a clock time.")],
    readback: "I'll book {patientName} into {department} on {date} at {time}. Shall I confirm?",
    expects: "confirmation, arriveBy (when to arrive, a phrase), bring (what to bring, a phrase).",
    speech: "Booked — confirmation {confirmation}. Please arrive by {arriveBy} and bring {bring}.",
    fallback: "The appointment is booked, though I couldn't get the confirmation just now. A text will follow with the time.",
  }),
  read({
    id: "look-up-appointment", sector: "Healthcare",
    name: "look_up_appointment",
    summary: "Reads a patient's next appointment from their hospital number.",
    description: "Look up a patient's next appointment by hospital number. Use it only for the patient themselves, or a parent for a child.",
    path: "/patients/{hospitalNumber}/appointments/next", params: [str("hospitalNumber", "The hospital number from the card.")],
    expects: "department, date (a phrase), time, doctor.",
    speech: "Your next appointment is {department} on {date} at {time}, with {doctor}.",
    fallback: "I can't see an upcoming appointment on that number. Would you like to book one?",
  }),
  read({
    id: "check-result-status", sector: "Healthcare",
    name: "check_result_status",
    summary: "Says whether a test result is ready for collection or needs a review — never what it says.",
    description: "Check whether a test result is ready. Use it for the patient only. It says whether it is ready and how it is released, never the result itself.",
    path: "/results/status", params: [str("hospitalNumber", "The hospital number from the patient's card."), str("test", "Which test it was, as the patient named it.")],
    expects: "status (pending, ready for collection, review needed), collectFrom (where, when ready), readyBy (when, if pending).",
    speech: "Your {test} result is {status}. Collect it from {collectFrom}.",
    fallback: "I can't see a result under that yet. The laboratory will call you when it's ready.",
  }),
  write({
    id: "request-refill", sector: "Healthcare",
    name: "request_refill",
    summary: "Requests a prescription refill for a patient and speaks when it can be collected.",
    description: "Request a prescription refill. Use it after taking the hospital number and the medication as printed on the pack.",
    path: "/prescriptions/refills",
    params: [str("hospitalNumber", "The hospital number from the patient's card."), str("medication", "The medication as printed on the pack."), str("phone", "A number to text when it's ready, digits only.")],
    readback: "A refill of {medication} on hospital number {hospitalNumber}, and I'll text {phone} when it's ready. Go ahead?",
    expects: "status (approved, needs review), collectBy (when it can be collected, a phrase).",
    speech: "The refill is {status}. It can be collected {collectBy}.",
    fallback: "The request is with the pharmacy, though I couldn't get a collection time. They will text you.",
  }),
  read({
    id: "check-drug-stock", sector: "Healthcare",
    name: "check_drug_stock",
    summary: "Checks whether a medicine is in stock and its price.",
    description: "Check whether a medicine or product is in stock at the pharmacy and what it costs. Use it when a caller asks for something by name.",
    path: "/stock", params: [str("item", "The medicine or product as the caller named it, including strength if they said it.")],
    expects: "inStock (yes or no), price (a number in naira, per pack), prescriptionOnly (yes or no).",
    speech: "{item} — in stock: {inStock}, at {price} naira a pack. Prescription needed: {prescriptionOnly}.",
    fallback: "I can't find that on the shelf list. The pharmacist will check and text you.",
  }),
  read({
    id: "check-hmo-cover", sector: "Healthcare",
    name: "check_hmo_cover",
    summary: "Checks an enrollee's plan and whether it is active — for the enrollee only.",
    description: "Check an enrollee's HMO plan by enrollee ID: which plan, whether it is active, and when it renews. Use it for the enrollee only.",
    path: "/enrollees/{enrolleeId}", params: [str("enrolleeId", "The enrollee ID from the card.")],
    expects: "plan, status (active, lapsed, suspended), renews (a date phrase), dependants (a count).",
    speech: "You're on the {plan} plan, currently {status}, renewing {renews}, with {dependants} dependants.",
    fallback: "I can't find an enrollee with that ID. Could you read it from the card once more?",
  }),
  irreversible({
    id: "issue-authorisation-code", sector: "Healthcare",
    name: "issue_authorisation_code",
    summary: "An authorisation code for treatment — the care line issues it, never the agent.",
    description: "Issue a pre-authorisation code for a treatment at a hospital. Never do this yourself.",
    path: "/authorisations", params: [str("enrolleeId", "The enrollee ID."), str("hospital", "The hospital they are at."), str("treatment", "The treatment.")],
    transferReason: "Authorisation codes are issued by the care line, who can see your plan. I'm putting you through to them now.",
  }),
];

/* ------------------------------------------------------- banking & fintech */
const FINANCE: readonly ToolTemplate[] = [
  read({
    id: "check-transaction-status", sector: "Banking & fintech",
    name: "check_transaction_status",
    summary: "Reads whether a transfer succeeded, failed or is pending, and whether a reversal is due.",
    description: "Check the status of a transaction by its reference or session ID. Use it when a caller says a transfer failed or money left their account.",
    path: "/transactions/{reference}", params: [str("reference", "The transaction reference or session ID from the receipt or alert.")],
    expects: "status (successful, failed, pending, reversed), amount (a number in naira), date (a phrase), reversalBy (when a reversal is due, if failed).",
    speech: "That transaction of {amount} naira on {date} is {status}. If a reversal is due, expect it by {reversalBy}.",
    fallback: "I can't find a transaction with that reference. A dispute can still be logged and the team will trace it.",
  }),
  write({
    id: "log-dispute", sector: "Banking & fintech",
    name: "log_dispute",
    summary: "Logs a transaction dispute and speaks the case number and the timeline.",
    description: "Log a dispute for a failed or wrong transaction. Use it after taking the date, amount, channel and reference.",
    path: "/disputes",
    params: [str("phone", "The caller's registered number, digits only."), str("date", "The transaction date."), num("amount", "The amount in naira."), str("channel", "transfer, USSD, POS, or ATM."), str("reference", "The reference, or 'none'.")],
    readback: "A dispute for {amount} naira by {channel} on {date}, reference {reference}. Shall I log it?",
    expects: "caseNumber, resolveBy (a phrase).",
    speech: "Logged — case number {caseNumber}. You'll hear back by {resolveBy}, and a text confirms it.",
    fallback: "The dispute is logged, though I couldn't get a case number just now. A text will follow.",
  }),
  irreversible({
    id: "block-card", sector: "Banking & fintech",
    name: "block_card",
    summary: "Blocking a card or account — a person does it, now, after confirming who is asking.",
    description: "Block a card or freeze an account because it is lost, stolen or being used by somebody else. Never do this yourself; put the caller through immediately.",
    path: "/cards/block", params: [str("phone", "The caller's registered number."), str("what", "the card, or the whole account.")],
    transferReason: "I'm putting you straight through to a person who will block it with you now.",
  }),
  read({
    id: "check-loan-eligibility", sector: "Banking & fintech",
    name: "check_loan_eligibility",
    summary: "Checks what a customer could borrow and over what term — not a rate, not an offer.",
    description: "Check a customer's loan eligibility by their registered number: the most they could borrow and the longest term. Use it after the caller has said how much they want.",
    path: "/loans/eligibility", params: [str("phone", "The customer's registered number, digits only."), num("amount", "How much they asked for, in naira.")],
    expects: "eligible (yes or no), maxAmount (a number in naira), maxMonths (a count).",
    speech: "Eligible: {eligible}. You could borrow up to {maxAmount} naira over up to {maxMonths} months. A loan officer confirms the rate.",
    fallback: "I can't check eligibility on that number right now. A loan officer will call you back.",
  }),
  write({
    id: "record-promise-to-pay", sector: "Banking & fintech",
    name: "record_promise_to_pay",
    summary: "Records the date and amount a borrower has promised to pay.",
    description: "Record a promise to pay from a borrower who will be late. Use it after they have said which day and how much.",
    path: "/repayments/promises",
    params: [str("loanReference", "The loan number, or the phone number the loan is on."), str("date", "The day they will pay."), num("amount", "How much they will pay that day, in naira.")],
    readback: "I'll note that you'll pay {amount} naira on {date}. Is that right?",
    expects: "recorded (yes or no), reminderOn (when a reminder text goes, a phrase).",
    speech: "Noted — thank you for calling ahead. A reminder text goes {reminderOn}.",
    fallback: "I've noted it for the loan officer, who will confirm it with you.",
  }),
];

/* ----------------------------------------------------------------- insurance */
const INSURANCE: readonly ToolTemplate[] = [
  read({
    id: "look-up-policy", sector: "Insurance",
    name: "look_up_policy",
    summary: "Reads an insurance policy's cover, status and renewal date from its number.",
    description: "Look up an insurance policy by its number: what it covers, whether it is active, and when it renews. Use it after reading the policy number back.",
    path: "/policies/{policyNumber}", params: [str("policyNumber", "The policy number, two letters and seven digits.")],
    expects: "cover (a phrase), status (active, lapsed, cancelled), renews (a date phrase), premium (a number in naira).",
    speech: "Policy {policyNumber} covers {cover}. It's {status} and renews {renews}; the premium is {premium} naira.",
    fallback: "I can't find a policy with that number. Could you read it to me one character at a time?",
  }),
  write({
    id: "log-claim", sector: "Insurance",
    name: "log_claim",
    summary: "Logs an insurance claim with what happened and speaks the claim number.",
    description: "Log an insurance claim. Use it after taking the policy number, the date and what happened.",
    path: "/claims",
    params: [str("policyNumber", "The policy number, as printed on the policy."), str("date", "When the event happened, as a date."), str("kind", "motor, health, or property."), str("detail", "What happened, in the caller's words.")],
    readback: "A {kind} claim on policy {policyNumber} for {date}: {detail}. Shall I log it?",
    expects: "claimNumber, assessor (who will call), by (when, a phrase).",
    speech: "Logged — claim number {claimNumber}. {assessor} will call you by {by}. Please photograph everything.",
    fallback: "The claim is logged, though I couldn't get a claim number just now. The claims team will text it.",
  }),
  irreversible({
    id: "cancel-policy", sector: "Insurance",
    name: "cancel_policy",
    summary: "Cancelling a policy or changing who is named on it — a person, always.",
    description: "Cancel a policy or change the people named on it. Never do this yourself.",
    path: "/policies/{policyNumber}/cancel", params: [str("policyNumber", "The policy number, as printed on the policy.")],
    transferReason: "Cancelling or changing a policy has to be confirmed with the policy team, so I'm putting you through to them now.",
  }),
  read({
    id: "check-claim-status", sector: "Insurance",
    name: "check_claim_status",
    summary: "Reads where a claim stands — received, being assessed, approved, paid — and what is still needed.",
    description: "Check the status of a claim by its claim number. Use it for the policyholder only, and never say whether it will be paid beyond what the status says.",
    path: "/claims/{claimNumber}", params: [str("claimNumber", "The claim number the caller was given.")],
    expects: "status (received, assessing, awaiting documents, approved, paid, declined), assessor, outstanding (what is still needed, a phrase or 'nothing').",
    speech: "Claim {claimNumber} is {status}, with {assessor}. Still needed from you: {outstanding}.",
    fallback: "I can't find a claim with that number. The claims team will check and call you back.",
  }),
  read({
    id: "get-renewal-quote", sector: "Insurance",
    name: "get_renewal_quote",
    summary: "Reads the renewal premium and expiry for a policy, and whether a discount applies.",
    description: "Get the renewal premium for a policy that is coming up for renewal. Use it when the policyholder asks what renewing will cost.",
    path: "/policies/{policyNumber}/renewal", params: [str("policyNumber", "The policy number, as printed on the policy.")],
    expects: "expires (a date phrase), premium (a number in naira), discount (a phrase, or 'none'), payBy (how to pay, a phrase).",
    speech: "Policy {policyNumber} expires {expires}. The renewal premium is {premium} naira; discount: {discount}. You can pay {payBy}.",
    fallback: "I can't see a renewal quote yet. The renewal notice will be sent by email and text.",
  }),
  write({
    id: "request-cover-quote", sector: "Insurance",
    name: "request_cover_quote",
    summary: "Requests quotations for new cover from the details taken, and speaks when they will arrive.",
    description: "Request quotations for new cover — motor, health, travel, property or business. Use it after taking what is to be covered and its rough value.",
    path: "/quotes",
    params: [str("name", "The caller's full name."), str("phone", "Their number, digits only."), str("kind", "motor, health, travel, property, or business."), str("detail", "What is being covered, as the caller described it."), num("value", "The rough value or sum, in naira, if they gave one.", false)],
    readback: "A {kind} quotation for {name}: {detail}. Shall I request it?",
    expects: "reference, by (when the quotes will arrive, a phrase), insurers (a count).",
    speech: "Requested — reference {reference}. Quotes from {insurers} insurers will reach you by {by}.",
    fallback: "The request is in; an adviser will send the quotations within one working day.",
  }),
];

/* ------------------------------------------------------ telecoms & internet */
const TELECOMS: readonly ToolTemplate[] = [
  read({
    id: "check-service-status", sector: "Telecoms & internet",
    name: "check_service_status",
    summary: "Checks whether an account's connection is up, and whether there's an outage in the area.",
    description: "Check an internet or TV account's service status: whether it is up, whether there is a known outage nearby, and when the subscription expires. Use it before logging a fault.",
    path: "/accounts/{accountId}/status", params: [str("accountId", "The account or customer ID from the invoice.")],
    expects: "link (up or down), areaOutage (yes or no), expires (a date phrase), plan.",
    speech: "Your link is {link}. Area outage: {areaOutage}. You're on {plan}, which runs until {expires}.",
    fallback: "I can't see that account. Could you check the ID on your invoice?",
  }),
  write({
    id: "log-fault", sector: "Telecoms & internet",
    name: "log_fault",
    summary: "Logs a connection fault after the restart check and speaks the ticket and the visit window.",
    description: "Log a service fault. Use it after the caller has restarted the router and it is still down.",
    path: "/faults",
    params: [str("accountId", "The account or customer ID from the invoice."), str("symptom", "What the caller sees — which lights, any error."), bool("restarted", "True if they have already switched the router off and on."), str("phone", "A number for the technician, digits only.")],
    readback: "Logging a fault on {accountId}: {symptom}. Restarted already: {restarted}. Shall I log it?",
    expects: "ticket, visitWindow (when a technician will call or come, a phrase).",
    speech: "Logged — ticket {ticket}. A technician will be in touch {visitWindow}.",
    fallback: "The fault is logged, though I couldn't get the ticket number. A text will follow.",
  }),
  read({
    id: "check-account-balance", sector: "Telecoms & internet",
    name: "check_account_balance",
    summary: "Reads what's owed on an account and when the next renewal is.",
    description: "Check an account's balance and next renewal date. Use it for the account holder only.",
    path: "/accounts/{accountId}/balance", params: [str("accountId", "The account or customer ID from the invoice.")],
    expects: "balance (a number in naira, zero when paid), renewsOn (a date phrase), plan.",
    speech: "The balance on {accountId} is {balance} naira. The {plan} renews {renewsOn}.",
    fallback: "I can't see that account's balance right now. Billing will text it to you.",
  }),
  write({
    id: "change-plan", sector: "Telecoms & internet",
    name: "change_plan",
    summary: "Moves an account to a different plan from the next renewal and speaks the new price.",
    description: "Change the plan on an account from the next renewal. Use it after the caller has chosen a plan by name.",
    path: "/accounts/{accountId}/plan", method: "PUT",
    params: [str("accountId", "The account or customer ID from the invoice."), str("plan", "The plan name the caller chose.")],
    readback: "I'll move {accountId} to the {plan} plan from your next renewal. Shall I confirm?",
    expects: "plan, price (a number in naira), from (a date phrase).",
    speech: "Done — you'll be on {plan} at {price} naira from {from}.",
    fallback: "The change is in, though I couldn't get the new price just now. A text confirms it.",
  }),
  write({
    id: "schedule-installation", sector: "Telecoms & internet",
    name: "schedule_installation",
    summary: "Books an installation at an address on a day and speaks the engineer's window.",
    description: "Schedule an installation of internet, a dish or a decoder at an address. Use it after coverage is confirmed and the caller has chosen a day.",
    path: "/installations",
    params: [str("name", "The customer's full name."), str("phone", "Their number, digits only."), str("address", "The address with a landmark."), str("date", "The day they want, as a date."), str("service", "internet, DStv, GOtv, Startimes, or the product named.")],
    readback: "An installation of {service} at {address} on {date}, for {name}. Shall I book it?",
    expects: "reference, window (the arrival window, a phrase), fee (a number in naira).",
    speech: "Booked — reference {reference}. The engineer will come {window}, and the installation fee is {fee} naira.",
    fallback: "The installation is booked, though I couldn't get the window just now. The engineer will call to confirm.",
  }),
  irreversible({
    id: "cancel-service", sector: "Telecoms & internet",
    name: "cancel_service",
    summary: "Closing an account — the retention team does it with the customer.",
    description: "Cancel a service and close the account. Never do this yourself.",
    path: "/accounts/{accountId}/cancel", params: [str("accountId", "The account or customer ID from the invoice.")],
    transferReason: "Closing an account is done with the retention team, so I'm putting you through to them now.",
  }),
];

/* ------------------------------------------------------- utilities & energy */
const UTILITIES: readonly ToolTemplate[] = [
  read({
    id: "check-outage", sector: "Utilities & energy",
    name: "check_outage",
    summary: "Checks whether there is a known outage on a feeder or in an area, and the estimated restoration.",
    description: "Check whether a power outage is known for a meter's feeder or an area. Use it before logging an outage report.",
    path: "/outages", params: [str("meter", "The meter or account number.", false), str("area", "The area or estate the caller named.", false)],
    expects: "known (yes or no), since (a phrase), restoreBy (a phrase), cause (a phrase).",
    speech: "Known outage: {known}. It's been off since {since} — {cause}. Restoration is expected {restoreBy}.",
    fallback: "There's no known outage there, so I'll log yours as a fault.",
  }),
  write({
    id: "log-outage", sector: "Utilities & energy",
    name: "log_outage",
    summary: "Logs a power outage against a meter and address and speaks the fault reference.",
    description: "Log a power outage or fault. Use it after taking the meter number, the address with a landmark and since when.",
    path: "/outages/reports",
    params: [str("meter", "The meter or account number."), str("address", "The address with a landmark."), str("since", "Since when, as the caller said it."), str("phone", "A number for updates, digits only.")],
    readback: "Logging an outage on meter {meter} at {address}, since {since}. Go ahead?",
    expects: "reference, feeder, dispatched (yes or no).",
    speech: "Logged — reference {reference}, on the {feeder} feeder. Field team dispatched: {dispatched}.",
    fallback: "It's logged, though I couldn't get a reference just now. You'll get a text.",
  }),
  read({
    id: "verify-token", sector: "Utilities & energy",
    name: "verify_token",
    summary: "Checks a prepaid token's status against the meter it was bought for.",
    description: "Verify a prepaid electricity token by the meter number and the purchase reference. Use it when a token will not load.",
    path: "/tokens/verify", params: [str("meter", "The prepaid meter number, digits only."), str("reference", "The purchase reference from the receipt.")],
    expects: "status (valid, used, wrong meter, not found), units (a number), issuedOn (a phrase).",
    speech: "That token is {status} — {units} units, issued {issuedOn}.",
    fallback: "I can't verify that token. The metering team will check with the receipt and call you back.",
  }),
  write({
    id: "schedule-gas-delivery", sector: "Utilities & energy",
    name: "schedule_gas_delivery",
    summary: "Books a cooking-gas refill or delivery and speaks the price and the rider's window.",
    description: "Schedule a cooking gas refill or cylinder delivery. Use it after taking the cylinder size, the count, the address and whether it is a refill or an exchange.",
    path: "/deliveries",
    params: [str("name", "The customer's full name."), str("phone", "Their number, digits only."), str("size", "3kg, 6kg, 12.5kg, 25kg, or 50kg."), num("count", "How many cylinders they want."), str("mode", "refill or exchange."), str("address", "The address with a landmark.")],
    readback: "{count} by {size}, {mode}, to {address}. Shall I send the rider?",
    expects: "total (a number in naira), window (a phrase), rider (a name).",
    speech: "The total is {total} naira and {rider} will be with you {window}.",
    fallback: "The order is in, though I couldn't get the total just now. It will be confirmed by text before the rider leaves.",
  }),
  read({
    id: "check-delivery-status", sector: "Utilities & energy",
    name: "check_delivery_status",
    summary: "Reads where a gas or water delivery is.",
    description: "Check the status of a delivery by its reference or the phone number it was ordered on.",
    path: "/deliveries/{reference}", params: [str("reference", "The delivery reference, or the phone number it was ordered on.")],
    expects: "status (scheduled, on the way, delivered), eta (a phrase), rider.",
    speech: "Your delivery is {status}. {rider} should reach you {eta}.",
    fallback: "I can't find a delivery under that. The dispatch desk will call you back.",
  }),
  write({
    id: "book-technician", sector: "Utilities & energy",
    name: "book_technician",
    summary: "Books a technician visit for a solar, borehole or generator system and speaks the window.",
    description: "Book a technician to visit an installation. Use it after taking the address, the system and the symptom.",
    path: "/visits",
    params: [str("phone", "The customer's number, digits only."), str("address", "The address with a landmark."), str("system", "solar, inverter, borehole, pump, or generator."), str("symptom", "What's wrong, in the caller's words."), str("date", "The day the caller wants.")],
    readback: "A technician for the {system} at {address} on {date}: {symptom}. Shall I book it?",
    expects: "reference, window (a phrase), technician.",
    speech: "Booked — reference {reference}. {technician} will come {window}.",
    fallback: "The visit is booked, though I couldn't get the window. The technician will call to confirm.",
  }),
];

/* ---------------------------------------------------- logistics & delivery */
const LOGISTICS: readonly ToolTemplate[] = [
  read({
    id: "track-shipment", sector: "Logistics & delivery",
    name: "track_shipment",
    summary: "Reads where a parcel is from its waybill number.",
    description: "Track a shipment by its waybill or tracking number. Use it when a caller asks where their parcel is.",
    path: "/shipments/{waybill}", params: [str("waybill", "The waybill or tracking number, letters and digits, no spaces.")],
    expects: "status (picked up, in transit, out for delivery, delivered, held), location, eta (a phrase).",
    speech: "Waybill {waybill} is {status}, last seen at {location}. Expected {eta}.",
    fallback: "I can't find that waybill. Could you read it once more, from the receipt?",
  }),
  read({
    id: "get-delivery-quote", sector: "Logistics & delivery",
    name: "get_delivery_quote",
    summary: "Quotes a delivery from pickup to drop-off for a parcel size and speed.",
    description: "Get a delivery price between two places for a parcel size and speed. Use it once both addresses and the size are known.",
    path: "/quotes", params: [str("from", "The pickup area or address."), str("to", "The drop-off area or address."), str("size", "small, medium, or large."), str("speed", "same day, next day, or standard.")],
    expects: "price (a number in naira), eta (a phrase).",
    speech: "From {from} to {to}, {size}, {speed}: {price} naira, delivered {eta}.",
    fallback: "I can't price that route right now. The rates desk will text you a quote.",
  }),
  write({
    id: "book-pickup", sector: "Logistics & delivery",
    name: "book_pickup",
    summary: "Books a pickup with both addresses and what's inside, and speaks the waybill and the rider's window.",
    description: "Book a courier pickup. Use it after taking both addresses with landmarks, what is in the package and when it is ready.",
    path: "/pickups",
    params: [str("senderName", "The sender's full name."), str("phone", "The sender's number, digits only."), str("from", "The pickup address with a landmark."), str("to", "The delivery address with a landmark."), str("item", "What is in the package and whether it is fragile."), str("readyBy", "When it is ready, as the caller said it.")],
    readback: "A pickup from {from} to {to} — {item} — ready {readyBy}. Shall I book it?",
    expects: "waybill, window (a phrase), price (a number in naira).",
    speech: "Booked — your waybill is {waybill}. The rider will come {window}, and it's {price} naira.",
    fallback: "The pickup is booked, though I couldn't get the waybill just now. Dispatch will text it.",
  }),
  read({
    id: "check-seat-availability", sector: "Logistics & delivery",
    name: "check_seat_availability",
    summary: "Checks seats and the fare on a bus route for a day and departure.",
    description: "Check seats and the fare on an interstate route for a day and departure. Use it before booking a seat.",
    path: "/routes/seats", params: [str("from", "The departure terminal or city."), str("to", "The destination city or airport."), str("date", "The date of travel, as a date."), str("departure", "morning or afternoon.")],
    expects: "seatsLeft (a count), fare (a number in naira), departsAt (a time phrase), bus (regular or luxury).",
    speech: "The {departure} {bus} bus from {from} to {to} leaves at {departsAt}; {seatsLeft} seats left at {fare} naira.",
    fallback: "That departure is full. Would the other departure, or another day, work?",
  }),
  write({
    id: "book-seat", sector: "Logistics & delivery",
    name: "book_seat",
    summary: "Holds seats on a departure under the passenger's name and speaks the booking and how long it's held.",
    description: "Book seats on a bus departure. Use it after availability is checked and you have the passenger's name and number.",
    path: "/routes/bookings",
    params: [str("name", "The passenger's full name."), str("phone", "Their number, digits only."), str("from", "The departure terminal."), str("to", "The destination city or airport."), str("date", "The date of travel, as a date."), str("departure", "morning or afternoon."), num("seats", "How many seats to book.")],
    readback: "{seats} seats for {name}, {from} to {to} on {date}, {departure} departure. Shall I hold them?",
    expects: "reference, heldFor (how long, a phrase), total (a number in naira).",
    speech: "Held — reference {reference}. The seats are held for {heldFor}; the total is {total} naira, and payment details are on their way by text.",
    fallback: "The seats are held, though I couldn't get the reference. The terminal will text it with the payment details.",
  }),
  write({
    id: "book-car", sector: "Logistics & delivery",
    name: "book_car",
    summary: "Books a hire car or airport pickup and speaks the driver and the fare.",
    description: "Book a hire car, chauffeur or airport pickup. Use it after taking the day, the time or flight, the pickup point and the car type.",
    path: "/hires",
    params: [str("name", "The passenger's full name."), str("phone", "Their number, digits only."), str("date", "The day they want, as a date."), str("time", "The pickup time, or the flight's arrival time."), str("pickup", "The pickup address with a landmark, or the airport and flight number."), str("car", "saloon, SUV, or bus."), str("kind", "airport pickup, full day, or a few hours.")],
    readback: "A {car} for {name} on {date} at {time}, from {pickup}, {kind}. Shall I book it?",
    expects: "reference, driver, fare (a number in naira).",
    speech: "Booked — reference {reference}. Your driver is {driver}, and the fare is {fare} naira. Their number comes by text on the day.",
    fallback: "The car is booked, though I couldn't get the fare just now. The driver's details and the fare will come by text.",
  }),
  irreversible({
    id: "cancel-booking", sector: "Logistics & delivery",
    name: "cancel_booking",
    summary: "Cancelling a seat, a car or a pickup — a person confirms it and any charge.",
    description: "Cancel a booking. Never do this yourself.",
    path: "/bookings/{reference}/cancel", params: [str("reference", "The booking reference the caller was given.")],
    transferReason: "A cancellation can carry a charge, so the bookings desk confirms it with you directly. Putting you through now.",
  }),
];

/* ----------------------------------------------------- retail & e-commerce */
const RETAIL: readonly ToolTemplate[] = [
  read({
    id: "check-stock", sector: "Retail & e-commerce",
    name: "check_stock",
    summary: "Checks whether an item is in stock and its price.",
    description: "Check whether a product is in stock and what it costs. Use it when a caller asks for something by name, model or size.",
    path: "/stock", params: [str("item", "The product as the caller named it, with model, size or brand if they said it."), num("quantity", "How many they want.", false)],
    expects: "inStock (yes or no), price (a number in naira, each), available (how many, a count).",
    speech: "{item} — in stock: {inStock}, at {price} naira each. We have {available}.",
    fallback: "I can't find that on the stock list. The shop will check and text you.",
  }),
  read({
    id: "look-up-order", sector: "Retail & e-commerce",
    name: "look_up_order",
    summary: "Reads an order's status and expected delivery from its number.",
    description: "Look up an order by its number to say where it is and when it will arrive. Use it when a caller asks where their order is.",
    path: "/orders/{orderNumber}", params: [str("orderNumber", "The order number from the confirmation message.")],
    expects: "status (processing, shipped, out for delivery, delivered, returned), eta (a phrase), items (a count).",
    speech: "Order {orderNumber} with {items} items is {status}. Expected {eta}.",
    fallback: "I can't find that order number. Could you check the confirmation message and read it again?",
  }),
  write({
    id: "start-return", sector: "Retail & e-commerce",
    name: "start_return",
    summary: "Opens a return or exchange for an item on an order and speaks the next step.",
    description: "Start a return or exchange for an item on an order. Use it after taking the order number, the item, the reason and whether they want a replacement or a refund.",
    path: "/returns",
    params: [str("orderNumber", "The order number from the confirmation."), str("item", "Which item on the order, as the caller named it."), str("reason", "What's wrong with it, in the caller's words."), str("want", "replacement or refund.")],
    readback: "A {want} for {item} on order {orderNumber}, because {reason}. Shall I open it?",
    expects: "returnNumber, nextStep (a phrase — a pickup, a drop-off, a label), eligible (yes or no).",
    speech: "Opened — return {returnNumber}. Eligible under the policy: {eligible}. Next: {nextStep}.",
    fallback: "The return is opened, though I couldn't get the number just now. The returns team will confirm by text.",
  }),
  write({
    id: "create-order", sector: "Retail & e-commerce",
    name: "create_order",
    summary: "Creates an order from a list in the caller's words, for delivery or pickup, and speaks the total.",
    description: "Create an order for delivery or pickup. Use it after reading the list back with quantities and taking the address for a delivery.",
    path: "/orders",
    params: [str("name", "The customer's full name."), str("phone", "Their number, digits only."), str("items", "The list with quantities, as the caller said it."), str("mode", "delivery or pickup."), str("address", "The delivery address with a landmark, or empty for pickup.", false), str("payment", "transfer, cash on delivery, or POS on delivery.")],
    readback: "Your order: {items}, for {mode}, paying by {payment}. Shall I place it?",
    expects: "orderNumber, total (a number in naira), eta (a phrase).",
    speech: "Order {orderNumber} placed. The total is {total} naira, and it'll be with you {eta}.",
    fallback: "The order is placed, though I couldn't get the total just now. It will be confirmed by text before it goes out.",
  }),
  read({
    id: "get-materials-quote", sector: "Retail & e-commerce",
    name: "get_materials_quote",
    summary: "Prices a building-materials list at today's prices and speaks the total.",
    description: "Price a list of building materials at today's prices. Use it after reading the list back with quantities.",
    path: "/quotes/materials", params: [str("items", "The list with quantities — bags of cement, lengths and sizes of rod, count of blocks — as the caller said it."), str("deliverTo", "The site area, for the delivery cost, or empty.", false)],
    expects: "total (a number in naira), delivery (a number in naira), validUntil (a phrase).",
    speech: "At today's prices that's {total} naira, plus {delivery} naira delivery. The quote holds until {validUntil}.",
    fallback: "I can't price the whole list right now. The trade desk will send a quotation by WhatsApp within the hour.",
  }),
];

/* ------------------------------------------------------ travel & transport */
const TRAVEL: readonly ToolTemplate[] = [
  read({
    id: "search-flights", sector: "Travel & transport",
    name: "search_flights",
    summary: "Finds the cheapest fare on a route for a date and class.",
    description: "Search flights on a route for a date and class and say the cheapest fare. Use it once the caller has said where, when and which class.",
    path: "/flights", params: [str("from", "The departure city or airport."), str("to", "The destination city or airport."), str("date", "The date of travel, as a date."), str("cabin", "economy or business."), bool("return", "True if a return is wanted.", false), str("returnDate", "The return date, if a return.", false)],
    expects: "count, cheapest.airline, cheapest.fare (a number in naira), cheapest.departs (a time phrase).",
    speech: "I found {count} options. The cheapest is {cheapest.airline} at {cheapest.fare} naira, departing {cheapest.departs}. Fares change by the hour, so a consultant will hold one for you.",
    fallback: "Nothing is showing for that route and date right now. A consultant will search wider and send options by WhatsApp.",
  }),
  write({
    id: "hold-booking", sector: "Travel & transport",
    name: "hold_booking",
    summary: "Holds a fare under the passenger's name as on the passport and speaks the PNR and how long it's held.",
    description: "Hold a flight booking. Use it after a fare is chosen and you have the passenger's name exactly as on the passport and their number.",
    path: "/bookings/hold",
    params: [str("passengerName", "The name exactly as written on the passport."), str("phone", "Their number, digits only."), str("from", "The departure city or airport."), str("to", "The destination city or airport."), str("date", "The date of travel, as a date."), str("cabin", "economy or business.")],
    readback: "Holding {cabin} from {from} to {to} on {date} for {passengerName}. Shall I hold it?",
    expects: "pnr, heldUntil (a phrase), fare (a number in naira).",
    speech: "Held — PNR {pnr}, until {heldUntil}, at {fare} naira. Payment details come by WhatsApp.",
    fallback: "The fare is held, though I couldn't get the PNR just now. The consultant will send it by WhatsApp.",
  }),
  read({
    id: "look-up-booking", sector: "Travel & transport",
    name: "look_up_booking",
    summary: "Reads a booking's status and travel date from its PNR or reference.",
    description: "Look up a booking by its PNR or reference to say whether it is ticketed and when it travels. Use it for the passenger only.",
    path: "/bookings/{reference}", params: [str("reference", "The PNR or booking reference.")],
    expects: "passenger, status (held, ticketed, cancelled), travels (a date phrase), route.",
    speech: "Booking {reference} for {passenger}, {route}, travelling {travels}, is {status}.",
    fallback: "I can't find a booking with that reference. Could it be under another one?",
  }),
  irreversible({
    id: "cancel-travel-booking", sector: "Travel & transport",
    name: "cancel_travel_booking",
    summary: "Cancelling a ticket or a tour — the consultant does it, with the fare rules in front of them.",
    description: "Cancel a flight, hotel or tour booking. Never do this yourself.",
    path: "/bookings/{reference}/cancel", params: [str("reference", "The booking reference the caller was given.")],
    transferReason: "Cancellations depend on the fare rules, so the consultant handling your booking confirms it with you. Putting you through now.",
  }),
];

/* --------------------------------------------------------------- education */
const EDUCATION: readonly ToolTemplate[] = [
  read({
    id: "look-up-fees", sector: "Education",
    name: "look_up_fees",
    summary: "Reads a pupil's fee balance and due date, for the parent on record only.",
    description: "Look up a pupil's school fee balance and due date. Use it only for the parent on record, after taking the pupil's name and class.",
    path: "/pupils/fees", params: [str("pupil", "The pupil's full name, as the parent said it."), str("form", "The class the pupil is in, as the parent said it.")],
    expects: "balance (a number in naira, zero when paid), due (a date phrase), term.",
    speech: "For {term}, the balance is {balance} naira, due {due}.",
    fallback: "I can't see that pupil's fees right now. The bursar will call you back.",
  }),
  write({
    id: "record-absence", sector: "Education",
    name: "record_absence",
    summary: "Records that a pupil will be absent, until when and why, for the class teacher.",
    description: "Record a pupil's absence. Use it after taking the pupil's name, class, the last day of absence and the reason.",
    path: "/absences",
    params: [str("pupil", "The pupil's full name, as the parent said it."), str("form", "The class the pupil is in, as the parent said it."), str("until", "The last day of absence."), str("reason", "The reason, briefly."), str("parentPhone", "The parent's number, digits only.")],
    readback: "I'll record that {pupil} in {form} will be away until {until}: {reason}. Shall I?",
    expects: "recorded (yes or no), teacher (the class teacher's name).",
    speech: "Recorded — {teacher} has been told. Please send a note when the child returns.",
    fallback: "It's noted for the class teacher, who will see it this morning.",
  }),
  read({
    id: "check-admission-status", sector: "Education",
    name: "check_admission_status",
    summary: "Reads where an application stands from its reference.",
    description: "Check the status of an admission application by its reference or JAMB number. Use it for the applicant or parent only.",
    path: "/admissions/{reference}", params: [str("reference", "The application reference or JAMB registration number.")],
    expects: "status (received, assessment scheduled, offered, declined, waitlisted), next (what happens next, a phrase), date (a date phrase, if scheduled).",
    speech: "Application {reference} is {status}. Next: {next}, on {date}.",
    fallback: "I can't find an application under that reference. Admissions will check and respond by email.",
  }),
  write({
    id: "book-assessment", sector: "Education",
    name: "book_assessment",
    summary: "Books an entrance assessment or a school visit and speaks the date and what to bring.",
    description: "Book an entrance assessment, an open day or a visit. Use it after taking the child's name and age, the class and the day.",
    path: "/assessments",
    params: [str("child", "The child's full name."), num("age", "The child's age in years."), str("form", "The class applied for."), str("parentPhone", "The parent's number, digits only."), str("date", "The day they want, as a date.")],
    readback: "An assessment for {child}, aged {age}, for {form}, on {date}. Shall I book it?",
    expects: "confirmation, time (a time phrase), bring (a phrase).",
    speech: "Booked — confirmation {confirmation}, at {time}. Please bring {bring}.",
    fallback: "The assessment is booked, though I couldn't get the time just now. Admissions will confirm by text.",
  }),
  read({
    id: "check-course-schedule", sector: "Education",
    name: "check_course_schedule",
    summary: "Reads the next cohort's start date, mode and fee for a course.",
    description: "Check when a course next starts, how it runs and what it costs. Use it once the caller has named a course.",
    path: "/courses", params: [str("course", "The course as the caller named it."), str("mode", "weekday, weekend, or online.", false)],
    expects: "starts (a date phrase), mode, weeks (a count), fee (a number in naira).",
    speech: "The next {course} cohort starts {starts}, {mode}, over {weeks} weeks, at {fee} naira. Instalments are available.",
    fallback: "I can't see a date for that course yet. Admissions will call with the next cohort.",
  }),
];

/* --------------------------------------------------------- faith & community */
const COMMUNITY: readonly ToolTemplate[] = [
  write({
    id: "log-prayer-request", sector: "Faith & community",
    name: "log_prayer_request",
    summary: "Records a prayer request for the prayer team and whether a pastor should call.",
    description: "Record a prayer request. Use it after the caller has said what they would like prayed about and whether they want a call.",
    path: "/prayer-requests",
    params: [str("name", "The caller's name, or 'anonymous'."), str("phone", "A number, if they want a call, digits only.", false), str("request", "The request, in their words."), bool("wantsCall", "True if they would like a pastor to call.")],
    readback: "I'll pass this to the prayer team: {request}. A pastor to call: {wantsCall}. Is that right?",
    expects: "received (yes or no), team.",
    speech: "It's with the {team} now. You're in our prayers.",
    fallback: "It's noted for the prayer team, who will pray over it today.",
  }),
  write({
    id: "record-pledge", sector: "Faith & community",
    name: "record_pledge",
    summary: "Records a donation or pledge and speaks how to pay and the receipt arrangement.",
    description: "Record a donation pledge. Use it after the caller has said how much and what it is for. Never take payment details.",
    path: "/pledges",
    params: [str("name", "The donor's full name."), str("phone", "Their number, digits only."), num("amount", "The amount in naira."), str("purpose", "What it is for — a project, general giving, zakat, welfare.")],
    readback: "A pledge of {amount} naira towards {purpose}, from {name}. Shall I record it?",
    expects: "reference, payBy (how to pay, a phrase — the account details go by text), receipt (a phrase).",
    speech: "Recorded — reference {reference}. Payment details come by text; {receipt}.",
    fallback: "Your pledge is recorded, and the accounts office will text the payment details.",
  }),
  write({
    id: "register-volunteer", sector: "Faith & community",
    name: "register_volunteer",
    summary: "Registers a volunteer with what they can do and when.",
    description: "Register a volunteer. Use it after taking their name, number, skills and availability.",
    path: "/volunteers",
    params: [str("name", "The caller's full name."), str("phone", "Their number, digits only."), str("skills", "What they can help with, in their words."), str("when", "weekdays, weekends, or either.")],
    readback: "Registering {name} for {skills}, available {when}. Shall I?",
    expects: "registered (yes or no), nextEvent (a phrase), coordinator.",
    speech: "Registered — {coordinator} will call about {nextEvent}.",
    fallback: "You're registered, and the volunteer coordinator will call you.",
  }),
  read({
    id: "check-event-schedule", sector: "Faith & community",
    name: "check_event_schedule",
    summary: "Reads the next service, prayer, meeting or programme of a kind.",
    description: "Check when the next service, prayer, meeting or programme of a kind is. Use it when a caller asks about times.",
    path: "/events/next", params: [str("kind", "What they asked about — Sunday service, Jumu'ah, midweek, AGM, outreach, or the programme named.")],
    expects: "name, when (a date and time phrase), where.",
    speech: "The next {name} is {when}, at {where}.",
    fallback: "I don't have a date for that yet. The office will confirm.",
  }),
];

/* ----------------------------------------------------- professional services */
const PROFESSIONAL: readonly ToolTemplate[] = [
  read({
    id: "check-matter-status", sector: "Professional services",
    name: "check_matter_status",
    summary: "Reads a client's matter or engagement status and the next date — for the client only.",
    description: "Check the status of a client's matter or engagement by its reference. Use it for the client only, and never discuss the substance.",
    path: "/matters/{reference}", params: [str("reference", "The matter or engagement reference.")],
    expects: "status (a phrase), handler (the lawyer or accountant), nextDate (a date phrase), nextStep (a phrase).",
    speech: "Matter {reference} is {status}, with {handler}. The next date is {nextDate}: {nextStep}.",
    fallback: "I can't find a matter under that reference. The handling lawyer will call you back.",
  }),
  write({
    id: "book-consultation", sector: "Professional services",
    name: "book_consultation",
    summary: "Books a consultation and speaks the fee and what to bring.",
    description: "Book a consultation with a lawyer, accountant or consultant. Use it after taking the area, a summary and a day and time.",
    path: "/consultations",
    params: [str("name", "The client's full name."), str("phone", "Their number, digits only."), str("area", "The area — property, family, tax, immigration, or as named."), str("summary", "What it is about, in one or two sentences."), str("date", "The day they want, as a date."), str("time", "The time they want, as a clock time.")],
    readback: "A {area} consultation for {name} on {date} at {time}: {summary}. Shall I book it?",
    expects: "confirmation, fee (a number in naira), bring (a phrase), with (who they will see).",
    speech: "Booked — confirmation {confirmation}, with {with}. The consultation fee is {fee} naira; please bring {bring}.",
    fallback: "The consultation is booked, though I couldn't get the fee just now. The office will confirm by email.",
  }),
  read({
    id: "check-filing-deadline", sector: "Professional services",
    name: "check_filing_deadline",
    summary: "Reads the next filing deadline for a company — annual returns, VAT, PAYE.",
    description: "Check the next filing deadline for a company by its RC number or TIN. Use it when a caller asks what is due.",
    path: "/filings/next", params: [str("company", "The RC number, BN number or TIN."), str("filing", "annual returns, VAT, PAYE, CIT, or any.", false)],
    expects: "filing, due (a date phrase), status (not started, in progress, filed).",
    speech: "The next filing is {filing}, due {due}. It's currently {status}.",
    fallback: "I can't see filings for that company. The compliance team will check and call back.",
  }),
  read({
    id: "get-print-quote", sector: "Professional services",
    name: "get_print_quote",
    summary: "Prices a print job from its spec and speaks the total and turnaround.",
    description: "Get a price for a print job. Use it after taking what, how many, the size and finish, and when it is needed.",
    path: "/quotes/print", params: [str("job", "What is being printed, quantity, size, paper or material, finish."), str("deadline", "When it is needed."), bool("needsDesign", "True if design is needed.")],
    expects: "price (a number in naira), turnaround (a phrase), rush (yes or no).",
    speech: "That's {price} naira, ready in {turnaround}. Rush job: {rush}.",
    fallback: "I can't price that automatically. The quotation will be sent by WhatsApp within the hour.",
  }),
  write({
    id: "record-vacancy", sector: "Professional services",
    name: "record_vacancy",
    summary: "Records an employer's vacancy for a consultant to pick up.",
    description: "Record a vacancy from an employer. Use it after taking the company, the role, how many and how urgent.",
    path: "/vacancies",
    params: [str("company", "The company's name, as the caller said it."), str("contactName", "The name of the person calling from the company."), str("phone", "Their number, digits only."), str("role", "The job title or role being hired for."), num("count", "How many positions are open."), bool("urgent", "True if urgent.")],
    readback: "{count} {role} positions at {company}, urgent: {urgent}. Shall I record it?",
    expects: "reference, consultant, by (when they will call, a phrase).",
    speech: "Recorded — reference {reference}. {consultant} will call you by {by} to take the brief.",
    fallback: "It's recorded, and a consultant will call within one working day.",
  }),
];

/* --------------------------------------------------- home & personal services */
const HOME_SERVICES: readonly ToolTemplate[] = [
  read({
    id: "check-technician-availability", sector: "Home & personal services",
    name: "check_technician_availability",
    summary: "Checks when a technician of a trade is free in an area.",
    description: "Check when a plumber, electrician, cleaner or other technician is next free in an area. Use it before booking a job.",
    path: "/technicians/availability", params: [str("trade", "plumbing, electrical, AC, carpentry, cleaning, fumigation, or as named."), str("area", "The area or neighbourhood the caller named."), str("date", "The day the caller wants.", false)],
    expects: "nextFree (a date and time phrase), technician, calloutFee (a number in naira).",
    speech: "The next {trade} technician free in {area} is {technician}, {nextFree}. The call-out fee is {calloutFee} naira, and they quote on site before starting.",
    fallback: "Nobody is free there that day. Would another day work?",
  }),
  write({
    id: "book-job", sector: "Home & personal services",
    name: "book_job",
    summary: "Books a home-service job and speaks the reference and the technician's window.",
    description: "Book a home-service job — a repair, an installation, a clean, a fumigation. Use it after taking the address with a landmark, what is needed and the day.",
    path: "/jobs",
    params: [str("name", "The customer's full name."), str("phone", "Their number, digits only."), str("trade", "The trade or service needed — plumbing, cleaning, fumigation, as named."), str("address", "The address with a landmark."), str("detail", "What is needed, in the caller's words."), str("date", "The day they want, as a date."), str("time", "morning or afternoon, or a time.")],
    readback: "A {trade} job at {address} on {date}, {time}: {detail}. Shall I book it?",
    expects: "reference, technician, window (a phrase).",
    speech: "Booked — reference {reference}. {technician} will come {window} and will quote before starting.",
    fallback: "The job is booked, though I couldn't get the reference just now. The technician will call to confirm.",
  }),
  read({
    id: "check-job-status", sector: "Home & personal services",
    name: "check_job_status",
    summary: "Reads where a booked job stands.",
    description: "Check the status of a booked job by its reference. Use it when a caller asks whether the technician is coming.",
    path: "/jobs/{reference}", params: [str("reference", "The job reference.")],
    expects: "status (scheduled, on the way, in progress, done), eta (a phrase), technician.",
    speech: "Job {reference} is {status}. {technician} should be with you {eta}.",
    fallback: "I can't find that job reference. Operations will call you back.",
  }),
  write({
    id: "book-salon-appointment", sector: "Home & personal services",
    name: "book_salon_appointment",
    summary: "Books a salon, barber or spa appointment with a stylist if asked, and speaks the confirmation.",
    description: "Book a salon, barber or spa appointment. Use it after taking the service, the day and time, and any stylist preference.",
    path: "/salon/appointments",
    params: [str("name", "The client's full name."), str("phone", "Their number, digits only."), str("service", "What they want done."), str("date", "The day they want, as a date."), str("time", "The time they want, as a clock time."), str("stylist", "The stylist they asked for, or empty.", false)],
    readback: "{service} for {name} on {date} at {time}. Shall I book it?",
    expects: "confirmation, stylist, duration (a phrase), deposit (a number in naira, zero if none).",
    speech: "Booked — confirmation {confirmation}, with {stylist}. Allow {duration}. Deposit: {deposit} naira.",
    fallback: "The appointment is booked, though I couldn't get the confirmation just now. A text will follow.",
  }),
];

/* --------------------------------------------------------- automotive & energy */
const AUTOMOTIVE: readonly ToolTemplate[] = [
  read({
    id: "check-vehicle-status", sector: "Automotive & energy",
    name: "check_vehicle_status",
    summary: "Reads where a car in the workshop stands, by job card or plate number.",
    description: "Check the status of a vehicle in the workshop by its job card number or plate number. Use it when a customer asks about their car.",
    path: "/workshop/jobs/{reference}", params: [str("reference", "The job card number, or the plate number.")],
    expects: "status (awaiting diagnosis, quoted, awaiting parts, in progress, ready), readyBy (a phrase), quote (a number in naira, if quoted).",
    speech: "Your car is {status}. Expected ready {readyBy}. The quote so far is {quote} naira.",
    fallback: "I can't find a job under that. The workshop floor will call you back.",
  }),
  write({
    id: "book-service", sector: "Automotive & energy",
    name: "book_service",
    summary: "Books a car in for servicing or repair, with pickup if asked, and speaks the slot.",
    description: "Book a vehicle in for servicing or a repair. Use it after taking the make, model and year, what it is doing, and the day.",
    path: "/workshop/bookings",
    params: [str("name", "The customer's full name."), str("phone", "Their number, digits only."), str("vehicle", "Make, model and year."), str("issue", "What it is doing, or the service wanted."), str("date", "The day they want, as a date."), bool("pickup", "True if the car should be collected."), str("address", "Where the car is, if pickup.", false)],
    readback: "{vehicle} on {date}: {issue}. Pickup: {pickup}. Shall I book it?",
    expects: "jobCard, slot (a time phrase), diagnosisFee (a number in naira).",
    speech: "Booked — job card {jobCard}, at {slot}. The diagnosis fee is {diagnosisFee} naira, and nothing is done without a quote.",
    fallback: "The booking is in, though I couldn't get the job card just now. The workshop will confirm by text.",
  }),
  read({
    id: "check-car-stock", sector: "Automotive & energy",
    name: "check_car_stock",
    summary: "Finds cars in stock by model, budget and condition.",
    description: "Search the dealership's stock by model or type, budget and condition. Use it once the caller has said what they want and their budget.",
    path: "/stock/cars", params: [str("wanted", "The model or type."), num("budget", "The budget in naira."), str("condition", "brand new, Tokunbo, Nigerian used, or any.")],
    expects: "count, top.model, top.year, top.price (a number in naira), top.stockNumber.",
    speech: "I found {count}. The closest is a {top.year} {top.model} at {top.price} naira, stock number {top.stockNumber}.",
    fallback: "Nothing in stock fits that exactly. An adviser will send what's close by WhatsApp.",
  }),
  read({
    id: "get-part-price", sector: "Automotive & energy",
    name: "get_part_price",
    summary: "Checks a spare part's availability and price for a vehicle or generator.",
    description: "Check whether a spare part is available and its price for a vehicle or generator model. Use it when a caller asks for a part by name.",
    path: "/parts", params: [str("model", "The vehicle or generator make, model and year or size."), str("part", "The part as the caller named it.")],
    expects: "available (yes or no), price (a number in naira), leadTime (a phrase, if not in stock).",
    speech: "{part} for {model} — available: {available}, at {price} naira. If ordering, allow {leadTime}.",
    fallback: "I can't find that part on the list. The parts desk will check and text you.",
  }),
];

/* ---------------------------------------------------------------- outbound */
const OUTBOUND: readonly ToolTemplate[] = [
  write({
    id: "record-outcome", sector: "Outbound",
    name: "record_call_outcome",
    summary: "Records what an outbound call came to — paid, promised, disputed, rescheduled, declined — for the campaign.",
    description: "Record the outcome of this outbound call. Use it once, at the end, with what the person said.",
    path: "/campaigns/outcomes",
    params: [str("phone", "The number called, digits only."), str("outcome", "One of: confirmed, rescheduled, cancelled, paid, promised, disputed, declined, not now, wrong number."), str("detail", "The date, amount or reason they gave, if any.", false)],
    readback: "I'll note this as {outcome}. Is that right?",
    expects: "recorded (yes or no), followUp (what happens next, a phrase).",
    speech: "Noted. {followUp}.",
    fallback: "Noted — thank you for your time.",
  }),
  write({
    id: "reschedule-appointment", sector: "Outbound",
    name: "reschedule_appointment",
    summary: "Moves an appointment to a new day and time and speaks the new slot.",
    description: "Move an existing appointment to a new day and time. Use it on a reminder call when the person cannot make the original.",
    path: "/appointments/{reference}/reschedule", method: "PUT",
    params: [str("reference", "The appointment reference the campaign carries."), str("date", "The new day."), str("time", "The new time.")],
    readback: "Moving your appointment to {date} at {time}. Shall I?",
    expects: "date (a phrase), time, with.",
    speech: "Done — you're now booked for {date} at {time}, with {with}. A text confirms it.",
    fallback: "The change is requested, though I couldn't confirm the exact slot. A text will confirm it.",
  }),
  write({
    id: "confirm-delivery", sector: "Outbound",
    name: "confirm_delivery",
    summary: "Confirms a delivery day with a landmark and who will receive it.",
    description: "Confirm a scheduled delivery. Use it on a delivery-confirmation call once the person has said they will be there, or who will receive it.",
    path: "/deliveries/{reference}/confirm", method: "PUT",
    params: [str("reference", "The delivery reference the campaign carries."), str("receiver", "Who will receive it."), str("landmark", "A landmark for the rider.")],
    readback: "So {receiver} will receive it, near {landmark}. Correct?",
    expects: "window (a phrase), rider.",
    speech: "Confirmed — {rider} will come {window} and call when close.",
    fallback: "Confirmed. The rider will call when close.",
  }),
  write({
    id: "record-survey", sector: "Outbound",
    name: "record_survey",
    summary: "Records a satisfaction score and comment, and whether a person should follow up.",
    description: "Record a survey answer. Use it at the end of a satisfaction call.",
    path: "/surveys",
    params: [str("phone", "The number called, digits only."), num("score", "The score out of ten."), str("comment", "What they said, in their words."), bool("followUp", "True if they want a person to call.")],
    readback: "A score of {score} out of ten, and I'll pass on: {comment}. Follow-up call: {followUp}. Right?",
    expects: "recorded (yes or no), thanks (a phrase).",
    speech: "{thanks}",
    fallback: "Thank you — that's recorded.",
  }),
];

export const TOOL_CATALOGUE: readonly ToolTemplate[] = [
  ...GENERAL, ...PROPERTY, ...HOSPITALITY, ...HEALTHCARE, ...FINANCE, ...INSURANCE, ...TELECOMS, ...UTILITIES, ...LOGISTICS,
  ...RETAIL, ...TRAVEL, ...EDUCATION, ...COMMUNITY, ...PROFESSIONAL, ...HOME_SERVICES, ...AUTOMOTIVE, ...OUTBOUND,
];

export const TOOL_SECTORS: readonly string[] = [...new Set(TOOL_CATALOGUE.map((tool) => tool.sector))];

export const findToolTemplate = (id: string): ToolTemplate | null => TOOL_CATALOGUE.find((tool) => tool.id === id) ?? null;
